-- Add Account Types
insert into AccountType values(0, 'None')
insert into AccountType values(1, 'Bank - Checking')
insert into AccountType values(2, 'Bank - Saving')
insert into AccountType values(3, 'Bank - Rewards')
insert into AccountType values(4, 'Debit Card')
insert into AccountType values(5, 'Credit Card')
insert into AccountType values(6, 'Home Loan')
insert into AccountType values(7, 'Auto Loan')
insert into AccountType values(8, '401K')
insert into AccountType values(9, 'Income Tax')
insert into AccountType values(10, 'Life Insurance')
insert into AccountType values(11, 'Health Insurance')
insert into AccountType values(12, 'Home Insurance')
insert into AccountType values(13, 'Auto Insurance')

